language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install: composer install

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then vendor/bin/phpunit ; fi

after_script: vendor/bin/php-coveralls --coverage_clover=clover.xml -v

notifications:
  email:
    on_success: never
