#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';

try {
    // Attempt to load .env and do nothing if it fails
    (new Dotenv\Dotenv(__DIR__.'/'))->load();
} catch (Dotenv\Exception\InvalidPathException $e) {
    //
}

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\HelperSet;
use Symfony\Component\Console\Helper\QuestionHelper;
use Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper;
use Doctrine\DBAL\Migrations\Tools\Console\Command as DoctrineCommand;

$app = require __DIR__ . '/bootstrap/app.php';
$db = $app->getContainer()->get('db');

$helperSet = new HelperSet([
    'db' => new ConnectionHelper($db),
    'dialog' => new QuestionHelper(),
]);

$cli = new Application();

$cli->setHelperSet($helperSet);

$cli->addCommands([
    new DoctrineCommand\DiffCommand(),
    new DoctrineCommand\ExecuteCommand(),
    new DoctrineCommand\GenerateCommand(),
    new DoctrineCommand\MigrateCommand(),
    new DoctrineCommand\StatusCommand(),
    new DoctrineCommand\VersionCommand(),
]);

$cli->run();
