#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';

try {
    // Attempt to load .env and do nothing if it fails
    (new Dotenv\Dotenv(__DIR__.'/'))->load();
} catch (Dotenv\Exception\InvalidPathException $e) {
    //
}

use Phpmig\Console\Command as PhpmigCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->addCommands([
    new PhpmigCommand\CheckCommand,
    new PhpmigCommand\DownCommand,
    new PhpmigCommand\GenerateCommand,
    new PhpmigCommand\InitCommand,
    new PhpmigCommand\MigrateCommand,
    new PhpmigCommand\RedoCommand,
    new PhpmigCommand\RollbackCommand,
    new PhpmigCommand\StatusCommand,
    new PhpmigCommand\UpCommand,
]);

$app->run();
