#!/usr/bin/env php
<?php

require __DIR__.'/bootstrap/autoload.php';
use Phpmig\Console\Command;

$app = require __DIR__.'/bootstrap/app.php';
$app->getContainer()->get('db'); // This will initialize the elequent capsule and make it global.

$application = new Symfony\Component\Console\Application();

$application->addCommands(array(
    new Command\InitCommand(),
    new Command\StatusCommand(),
    new Command\CheckCommand(),
    new Command\GenerateCommand(),
    new Command\UpCommand(),
    new Command\DownCommand(),
    new Command\MigrateCommand(),
    new Command\RollbackCommand(),
    new Command\RedoCommand()
));

$application->run();
